<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.igormaznitsa</groupId>
        <artifactId>nano-vllm-java-pom</artifactId>
        <version>1.3.1-SNAPSHOT</version>
    </parent>

    <artifactId>nano-vllm-java-samples</artifactId>
    <name>nano-vllm-java-samples</name>
    <description>Sample applications and demos for nano-vllm-java</description>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
        <exec.mainClass>com.igormaznitsa.nanollvm.samples.Example</exec.mainClass>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.igormaznitsa</groupId>
            <artifactId>nano-vllm-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <configuration>
                    <workingDirectory>${maven.multiModuleProjectDirectory}</workingDirectory>
                    <mainClass>${exec.mainClass}</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
